In [11]:
import numpy as np

def gauss_jordan(matriks, vektor):
    n = len(matriks)

    augmented_matriks = np.column_stack((matriks, vektor))

    for i in range(n):
        # Pencarian elemen dengan nilai mutlak terbesar di bawah atau pada diagonal
        max_row = i
        for j in range(i + 1, n):
            if abs(augmented_matriks[j][i]) > abs(augmented_matriks[max_row][i]):
                max_row = j

        # Penukaran baris
        augmented_matriks[[i, max_row]] = augmented_matriks[[max_row, i]]

        # Membuat elemen diagonal menjadi 1
        augmented_matriks[i] = augmented_matriks[i] / augmented_matriks[i][i]

        # Menghilangkan elemen-elemen di atas dan di bawah elemen diagonal
        for j in range(n):
            if j != i:
                augmented_matriks[j] -= augmented_matriks[j][i] * augmented_matriks[i]

        # Tampilkan matriks pada setiap langkah
        print(f"\nLangkah {i+1}:")
        for row in augmented_matriks:
            print(row)

    return augmented_matriks

# Mengambil input dari pengguna untuk matriks dan vektor
n = int(input("Masukkan jumlah baris dan kolom matriks: "))
matriks = []
for i in range(n):
    row = []
    for j in range(n):
        element = float(input(f"Masukkan elemen baris {i+1}, kolom {j+1} matriks: "))
        row.append(element)
    matriks.append(row)

vektor = []
for i in range(n):
    element = float(input(f"Masukkan elemen ke-{i+1} vektor: "))
    vektor.append(element)

# Mengambil input dari pengguna untuk rentang nomor random pada baris ketiga, kolom ketiga
start_range = int(input("Masukkan rentang awal nomor random: "))
end_range = int(input("Masukkan rentang akhir nomor random: "))

# Menghasilkan nomor random untuk baris ketiga, kolom ketiga
matriks[2][2] = np.random.randint(start_range, end_range+1)

# Menampilkan matriks dan vektor sebelum dilakukan eliminasi Gauss-Jordan
print("Matriks dan vektor sebelum eliminasi Gauss-Jordan:")
for i in range(n):
    print(matriks[i], "|", vektor[i])

# Melakukan eliminasi Gauss-Jordan
augmented_matriks = gauss_jordan(np.array(matriks), np.array(vektor))

# Menampilkan matriks dan vektor setelah eliminasi Gauss-Jordan
print("\nMatriks dan vektor setelah eliminasi Gauss-Jordan:")
for i in range(n):
    print(augmented_matriks[i, :-1], "|", augmented_matriks[i, -1])

# Mencetak solusi persamaan
print("\nSolusi persamaan:")
for i in range(n):
    print(f"x{i+1} =", augmented_matriks[i, -1])

Masukkan jumlah baris dan kolom matriks: 3
Masukkan elemen baris 1, kolom 1 matriks: 27
Masukkan elemen baris 1, kolom 2 matriks: 6
Masukkan elemen baris 1, kolom 3 matriks: -1
Masukkan elemen baris 2, kolom 1 matriks: 6
Masukkan elemen baris 2, kolom 2 matriks: 15
Masukkan elemen baris 2, kolom 3 matriks: 2
Masukkan elemen baris 3, kolom 1 matriks: 1
Masukkan elemen baris 3, kolom 2 matriks: 1
Masukkan elemen baris 3, kolom 3 matriks: 0
Masukkan elemen ke-1 vektor: 85
Masukkan elemen ke-2 vektor: 72
Masukkan elemen ke-3 vektor: 110
Masukkan rentang awal nomor random: 1
Masukkan rentang akhir nomor random: 40
Matriks dan vektor sebelum eliminasi Gauss-Jordan:
[27.0, 6.0, -1.0] | 85.0
[6.0, 15.0, 2.0] | 72.0
[1.0, 1.0, 26] | 110.0

Langkah 1:
[ 1.          0.22222222 -0.03703704  3.14814815]
[ 0.         13.66666667  2.22222222 53.11111111]
[  0.           0.77777778  26.03703704 106.85185185]

Langkah 2:
[ 1.          0.         -0.07317073  2.28455285]
[0.         1.         0.1626016